-- Generated PostgreSQL Canonical DDL

CREATE SCHEMA IF NOT EXISTS "core";
CREATE SCHEMA IF NOT EXISTS "inventory";
CREATE SCHEMA IF NOT EXISTS "sales";
CREATE SCHEMA IF NOT EXISTS "audit";

CREATE TABLE IF NOT EXISTS "audit"."audit_logs" (
    "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "schema_name" VARCHAR(50) NOT NULL,
    "table_name" VARCHAR(100) NOT NULL,
    "record_key" VARCHAR(100) NOT NULL,
    "action_type" VARCHAR(10) NOT NULL,
    "changed_by" VARCHAR(100) NOT NULL,
    "changed_at" TIMESTAMPTZ NOT NULL,
    "old_values_json" TEXT,
    "new_values_json" TEXT,
    CONSTRAINT "pk_audit_logs" PRIMARY KEY ("log_id")
);

CREATE TABLE IF NOT EXISTS "audit"."system_configurations" (
    "config_key" VARCHAR(100) NOT NULL,
    "config_value" TEXT NOT NULL,
    "data_type" VARCHAR(20) NOT NULL,
    "description" VARCHAR(255),
    "is_encrypted" BOOLEAN NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_system_configurations" PRIMARY KEY ("config_key")
);

CREATE TABLE IF NOT EXISTS "core"."countries" (
    "country_code" CHAR(2) NOT NULL,
    "country_name" VARCHAR(100) NOT NULL,
    "currency_code" CHAR(3) NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    CONSTRAINT "pk_countries" PRIMARY KEY ("country_code")
);

CREATE TABLE IF NOT EXISTS "core"."customer_addresses" (
    "address_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "customer_id" INTEGER NOT NULL,
    "address_type" VARCHAR(20) NOT NULL,
    "line1" VARCHAR(150) NOT NULL,
    "line2" VARCHAR(150),
    "city" VARCHAR(100) NOT NULL,
    "state" VARCHAR(50),
    "postal_code" VARCHAR(20) NOT NULL,
    "country_code" CHAR(2) NOT NULL,
    "is_default" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_customer_addresses" PRIMARY KEY ("address_id")
);

CREATE TABLE IF NOT EXISTS "core"."customer_profiles" (
    "profile_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "customer_id" INTEGER NOT NULL,
    "loyalty_tier" VARCHAR(20) NOT NULL,
    "loyalty_points" INTEGER NOT NULL,
    "preferred_currency" CHAR(3) NOT NULL,
    "marketing_opt_in" BOOLEAN NOT NULL,
    "bio" VARCHAR(500),
    "preferences_xml" TEXT,
    "last_login_at" TIMESTAMPTZ,
    CONSTRAINT "pk_customer_profiles" PRIMARY KEY ("profile_id")
);

CREATE TABLE IF NOT EXISTS "core"."customers" (
    "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "customer_guid" UUID NOT NULL,
    "customer_type" VARCHAR(20) NOT NULL,
    "company_name" VARCHAR(150),
    "contact_name" VARCHAR(100) NOT NULL,
    "email" VARCHAR(150) NOT NULL,
    "phone" VARCHAR(30),
    "tax_number" VARCHAR(50),
    "credit_limit" NUMERIC(12,2) NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "metadata_json" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    CONSTRAINT "pk_customers" PRIMARY KEY ("customer_id")
);

CREATE TABLE IF NOT EXISTS "core"."departments" (
    "department_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "department_code" VARCHAR(20) NOT NULL,
    "department_name" VARCHAR(100) NOT NULL,
    "budget" NUMERIC(14,2) NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    CONSTRAINT "pk_departments" PRIMARY KEY ("department_id")
);

CREATE TABLE IF NOT EXISTS "core"."employees" (
    "employee_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "department_id" INTEGER NOT NULL,
    "manager_employee_id" INTEGER,
    "first_name" VARCHAR(50) NOT NULL,
    "last_name" VARCHAR(50) NOT NULL,
    "job_title" VARCHAR(100) NOT NULL,
    "email" VARCHAR(150) NOT NULL,
    "phone" VARCHAR(30),
    "hire_date" DATE NOT NULL,
    "salary" NUMERIC(12,2) NOT NULL,
    "commission_rate" NUMERIC(5,4) NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_employees" PRIMARY KEY ("employee_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."categories" (
    "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "parent_category_id" INTEGER,
    "category_code" VARCHAR(50) NOT NULL,
    "category_name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(500),
    "is_active" BOOLEAN NOT NULL,
    CONSTRAINT "pk_categories" PRIMARY KEY ("category_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."inventory_transactions" (
    "transaction_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INTEGER NOT NULL,
    "warehouse_id" INTEGER NOT NULL,
    "transaction_type" VARCHAR(30) NOT NULL,
    "quantity_delta" INTEGER NOT NULL,
    "reference_document" VARCHAR(100),
    "notes" VARCHAR(500),
    "transaction_date" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_inventory_transactions" PRIMARY KEY ("transaction_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."product_brands" (
    "brand_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "brand_code" VARCHAR(50) NOT NULL,
    "brand_name" VARCHAR(100) NOT NULL,
    "website_url" VARCHAR(255),
    "is_active" BOOLEAN NOT NULL,
    CONSTRAINT "pk_product_brands" PRIMARY KEY ("brand_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."product_inventory" (
    "product_id" INTEGER NOT NULL,
    "warehouse_id" INTEGER NOT NULL,
    "quantity_on_hand" INTEGER NOT NULL,
    "quantity_reserved" INTEGER NOT NULL,
    "reorder_point" INTEGER NOT NULL,
    "safety_stock" INTEGER NOT NULL,
    "last_restocked_at" TIMESTAMPTZ,
    CONSTRAINT "pk_product_inventory" PRIMARY KEY ("product_id", "warehouse_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."products" (
    "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "sku" VARCHAR(50) NOT NULL,
    "product_name" VARCHAR(200) NOT NULL,
    "brand_id" INTEGER NOT NULL,
    "category_id" INTEGER NOT NULL,
    "primary_supplier_id" INTEGER NOT NULL,
    "unit_cost" NUMERIC(12,4) NOT NULL,
    "list_price" NUMERIC(12,2) NOT NULL,
    "weight_kg" NUMERIC(8,3),
    "dimensions_cm" VARCHAR(50),
    "barcode" VARCHAR(100),
    "is_discontinued" BOOLEAN NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    CONSTRAINT "pk_products" PRIMARY KEY ("product_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."product_variants" (
    "variant_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INTEGER NOT NULL,
    "variant_sku" VARCHAR(50) NOT NULL,
    "color" VARCHAR(50),
    "size" VARCHAR(20),
    "material" VARCHAR(50),
    "price_delta" NUMERIC(8,2) NOT NULL,
    "barcode" VARCHAR(100),
    "is_active" BOOLEAN NOT NULL,
    CONSTRAINT "pk_product_variants" PRIMARY KEY ("variant_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."suppliers" (
    "supplier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "supplier_name" VARCHAR(150) NOT NULL,
    "contact_name" VARCHAR(100) NOT NULL,
    "email" VARCHAR(150) NOT NULL,
    "phone" VARCHAR(30),
    "rating" SMALLINT NOT NULL,
    "is_preferred" BOOLEAN NOT NULL,
    "payment_terms_days" SMALLINT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_suppliers" PRIMARY KEY ("supplier_id")
);

CREATE TABLE IF NOT EXISTS "inventory"."warehouses" (
    "warehouse_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "warehouse_code" VARCHAR(20) NOT NULL,
    "warehouse_name" VARCHAR(100) NOT NULL,
    "country_code" CHAR(2) NOT NULL,
    "city" VARCHAR(100) NOT NULL,
    "capacity_sq_ft" INTEGER NOT NULL,
    "is_bonded" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_warehouses" PRIMARY KEY ("warehouse_id")
);

CREATE TABLE IF NOT EXISTS "sales"."customer_reviews" (
    "review_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "customer_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "rating" SMALLINT NOT NULL,
    "review_title" VARCHAR(150) NOT NULL,
    "review_body" TEXT,
    "is_verified_purchase" BOOLEAN NOT NULL,
    "is_approved" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_customer_reviews" PRIMARY KEY ("review_id")
);

CREATE TABLE IF NOT EXISTS "sales"."invoices" (
    "invoice_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "invoice_number" VARCHAR(50) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "invoice_date" DATE NOT NULL,
    "due_date" DATE NOT NULL,
    "sub_total" NUMERIC(14,2) NOT NULL,
    "tax_amount" NUMERIC(14,2) NOT NULL,
    "total_amount" NUMERIC(14,2) NOT NULL,
    "amount_paid" NUMERIC(14,2) NOT NULL,
    "balance_due" NUMERIC(14,2) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    CONSTRAINT "pk_invoices" PRIMARY KEY ("invoice_id")
);

CREATE TABLE IF NOT EXISTS "sales"."order_discounts" (
    "order_id" BIGINT NOT NULL,
    "promotion_id" INTEGER NOT NULL,
    "discount_applied" NUMERIC(10,2) NOT NULL,
    CONSTRAINT "pk_order_discounts" PRIMARY KEY ("order_id", "promotion_id")
);

CREATE TABLE IF NOT EXISTS "sales"."order_fulfillments" (
    "fulfillment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "order_id" BIGINT NOT NULL,
    "warehouse_id" INTEGER NOT NULL,
    "carrier" VARCHAR(50) NOT NULL,
    "tracking_number" VARCHAR(100),
    "status" VARCHAR(30) NOT NULL,
    "shipped_at" TIMESTAMPTZ,
    "delivered_at" TIMESTAMPTZ,
    CONSTRAINT "pk_order_fulfillments" PRIMARY KEY ("fulfillment_id")
);

CREATE TABLE IF NOT EXISTS "sales"."order_items" (
    "order_item_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "order_id" BIGINT NOT NULL,
    "line_number" SMALLINT NOT NULL,
    "product_id" INTEGER NOT NULL,
    "variant_id" INTEGER,
    "quantity" INTEGER NOT NULL,
    "unit_price" NUMERIC(12,2) NOT NULL,
    "discount_amount" NUMERIC(10,2) NOT NULL,
    "total_line_price" NUMERIC(14,2) NOT NULL,
    "notes" VARCHAR(255),
    CONSTRAINT "pk_order_items" PRIMARY KEY ("order_item_id")
);

CREATE TABLE IF NOT EXISTS "sales"."order_notes" (
    "note_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "order_id" BIGINT NOT NULL,
    "author_employee_id" INTEGER NOT NULL,
    "note_text" TEXT NOT NULL,
    "is_internal_only" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "pk_order_notes" PRIMARY KEY ("note_id")
);

CREATE TABLE IF NOT EXISTS "sales"."orders" (
    "order_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "order_number" VARCHAR(50) NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "sales_rep_employee_id" INTEGER,
    "shipping_address_id" INTEGER,
    "order_status" SMALLINT NOT NULL,
    "order_date" TIMESTAMPTZ NOT NULL,
    "required_date" TIMESTAMPTZ,
    "shipped_date" TIMESTAMPTZ,
    "sub_total" NUMERIC(14,2) NOT NULL,
    "tax_amount" NUMERIC(14,2) NOT NULL,
    "shipping_cost" NUMERIC(10,2) NOT NULL,
    "discount_total" NUMERIC(14,2) NOT NULL,
    "total_amount" NUMERIC(14,2) NOT NULL,
    "payment_status" VARCHAR(20) NOT NULL,
    "special_instructions" VARCHAR(1000),
    CONSTRAINT "pk_orders" PRIMARY KEY ("order_id")
);

CREATE TABLE IF NOT EXISTS "sales"."payments" (
    "payment_id" UUID NOT NULL,
    "invoice_id" BIGINT NOT NULL,
    "customer_id" INTEGER NOT NULL,
    "payment_method" VARCHAR(30) NOT NULL,
    "amount" NUMERIC(14,2) NOT NULL,
    "currency_code" CHAR(3) NOT NULL,
    "transaction_reference" VARCHAR(100) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "processed_at" TIMESTAMPTZ NOT NULL,
    "gateway_response" TEXT,
    CONSTRAINT "pk_payments" PRIMARY KEY ("payment_id")
);

CREATE TABLE IF NOT EXISTS "sales"."price_lists" (
    "price_list_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "price_list_name" VARCHAR(100) NOT NULL,
    "currency_code" CHAR(3) NOT NULL,
    "valid_from" DATE NOT NULL,
    "valid_to" DATE NOT NULL,
    "is_default" BOOLEAN NOT NULL,
    CONSTRAINT "pk_price_lists" PRIMARY KEY ("price_list_id")
);

CREATE TABLE IF NOT EXISTS "sales"."promotions" (
    "promotion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "promo_code" VARCHAR(50) NOT NULL,
    "promo_name" VARCHAR(100) NOT NULL,
    "discount_percent" NUMERIC(5,2) NOT NULL,
    "min_order_amount" NUMERIC(10,2) NOT NULL,
    "start_date" TIMESTAMPTZ NOT NULL,
    "end_date" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    CONSTRAINT "pk_promotions" PRIMARY KEY ("promotion_id")
);

-- Canonical Views
CREATE OR REPLACE VIEW sales.vw_customer_order_summary AS
        SELECT 
            c.customer_id,
            c.contact_name,
            c.company_name,
            c.customer_type,
            COUNT(o.order_id) AS total_orders_placed,
            COALESCE(SUM(o.total_amount), 0.00) AS lifetime_order_value,
            MAX(o.order_date) AS most_recent_order_date,
            AVG(o.total_amount) AS average_order_value
        FROM core.customers c
        LEFT JOIN sales.orders o ON c.customer_id = o.customer_id
        GROUP BY 
            c.customer_id,
            c.contact_name,
            c.company_name,
            c.customer_type;

CREATE OR REPLACE VIEW inventory.vw_low_stock_products AS
        SELECT 
            p.product_id,
            p.sku,
            p.product_name,
            w.warehouse_code,
            w.warehouse_name,
            inv.quantity_on_hand,
            inv.quantity_reserved,
            inv.reorder_point,
            (inv.quantity_on_hand - inv.quantity_reserved) AS available_stock,
            CASE 
                WHEN (inv.quantity_on_hand - inv.quantity_reserved) <= inv.reorder_point THEN 'REORDER_NOW'
                WHEN (inv.quantity_on_hand - inv.quantity_reserved) <= (inv.reorder_point + inv.safety_stock) THEN 'LOW_WARNING'
                ELSE 'SUFFICIENT'
            END AS stock_status
        FROM inventory.product_inventory inv
        JOIN inventory.products p ON inv.product_id = p.product_id
        JOIN inventory.warehouses w ON inv.warehouse_id = w.warehouse_id
        WHERE (inv.quantity_on_hand - inv.quantity_reserved) <= (inv.reorder_point + inv.safety_stock);

